### ISSUE TITLE
Could you please provide a download link to the cifar10_ssba_train_b1.npy for running issba attack?

### ISSUE THREAD

**Issue by RorschachChen** [SCLBD/BackdoorBench#1]
FileNotFoundError: [Errno 2] No such file or directory: '../resource/ssba/cifar10_ssba_train_b1.npy'

**Comment by CHR-ray** [comment]
https://drive.google.com/drive/folders/1QU771F2_1mKgfNQZm3OMCyegu2ONJiU2?usp=sharing

You should notice that since SSBA uses an autoencoder-like network to generate the poisoned samples, the hyper-parameters used in the training process and poison process may influence the final performance. 

Here, we only use 1-bit information to do the poisoning process such that it can be as imperceptible as possible for low-resolution datasets. (For 224 * 224 pictures, SSBA uses more information to do the poisoning as its standard since larger resolution allows higher information embedded.) 

We have not tried the poisoning process with a more significant amount of information. And it is possible to improve the attack performance with a more significant amount of information embedded.

**Comment by RorschachChen** [comment]
Thanks very much for your kindly sharing!
