### ISSUE TITLE
A data loading problem of LC attack

### ISSUE THREAD

**Issue by 1180200525** [SCLBD/BackdoorBench#16]
V2.0版本中[Label Consistent](https://github.com/SCLBD/BackdoorBench/blob/main/attack/lc.py)的数据加载存在一些问题。
在LS攻击的毒化数据生成代码[craft_adv_dataset.py](https://github.com/SCLBD/BackdoorBench/blob/main/resource/label-consistent/craft_adv_dataset.py)中，图像和标签被统一保存了下来，并以**npz**格式存储，然而在[Label Consistent](https://github.com/SCLBD/BackdoorBench/blob/main/attack/lc.py)中的89行和95行默认读取的文件格式为**npy**。

[craft_adv_dataset.py](https://github.com/SCLBD/BackdoorBench/blob/main/resource/label-consistent/craft_adv_dataset.py)中将图像和标签统一保存为npz格式：
https://github.com/SCLBD/BackdoorBench/blob/9df0c6c53dfc824cb9b228751beb5d05d735a383/resource/label-consistent/craft_adv_dataset.py#L775-L778
[Label Consistent.py](https://github.com/SCLBD/BackdoorBench/blob/main/resource/label-consistent/craft_adv_dataset.py)中的默认读取格式为npy：
https://github.com/SCLBD/BackdoorBench/blob/9df0c6c53dfc824cb9b228751beb5d05d735a383/attack/lc.py#L89-L92

**Comment by CHR-ray** [comment]
Thank you for your comment. Since the files I updated to google drive is in npy format, I decide to change the generation part instead of loading part to keep the consistency. You can find the update in recent commit [4eb9c8b](https://github.com/SCLBD/BackdoorBench/commit/4eb9c8b1a9b29af3e1ce95a3beac5ab533a0d7b4).
