### ISSUE TITLE
How to use this library in an incremental manner?

### ISSUE THREAD

**Issue by jsrdcht** [SCLBD/BackdoorBench#34]
Assuming I have developed some new features on top of the library, how do I merge them into the existing code when BackdoorBench is updated?

**Comment by CHR-ray** [comment]
Hi jsrdcht,
Sorry to reply late. This is too general a question, so I can only answer what I think you are asking.
What you want to ask is that if one day you are building some functions or scripts on top of our benchmark, and soon we update our benchmark, how can we guarantee your code is still working correctly?
For this question, I think it is usually not a big problem. Since we are now also incrementally developing this benchmark, which means if there is no big problem or framework issue, we only plan to add methods to this benchmark without changing the underlying framework. Also, for utils and other framework components, we usually add functions or classes to satisfy further functionality requirements without modifying those already built blocks.
