### ISSUE TITLE
Poison Index Selection - Clean label case

### ISSUE THREAD

**Issue by WhoDunnett** [SCLBD/BackdoorBench#36]
Hi BackdooorBench Team,

I think I have found a small issue with the backdoor poison index selection method. In the case where a clean label attack is used, the index selection method errors in some cases. I believe the issue is caused by the pratio not being multiplied by the correct length operator. The issue is on line 59 of "backdoor_generate_poison_index.py." I have provided a code snippet below of the issue and how I think it should be fixed. Notice that pratio should be multiplied by len(np.where(targets == tlabel)[0]) rather then len(targets). 

non_zero_array = np.random.choice(np.where(targets == tlabel)[0], round(pratio * len(targets)), replace = False)
non_zero_array = np.random.choice(np.where(targets == tlabel)[0], round(pratio * len(np.where(targets == tlabel)[0])), replace = False)

**Comment by CHR-ray** [comment]
Hello WhoDunnett,
I actually considered this question before. The main concern is that if we use this definition, the poisoning ratio for dirty-label and clean-label would be based on different totals, which I believe would lead to some degree of ambiguity. So, I did not adopt this definition for attacks on clean-label. In order to maintain consistency in parameter definition, I sacrificed some convenience.

**Comment by WhoDunnett** [comment]
Hi Ray,

Thank you for your reply. I do see how this could create confusion. However, I do believe this is how the poisoning ratio was defined by the authors of the SIG attack. In addition, it creates issues when the pratio multiplied by the length of the dataset is greater then the length of the number of samples in the given class. The reason I mention this is because I ran into this problem when using GTSRB.
