### ISSUE TITLE
bpp attack source

### ISSUE THREAD

**Issue by FZU-LW** [SCLBD/BackdoorBench#37]
Thank you for your great work! 
I would like to know why the file "cifar10_preactresnet18_bpp_0_1.zip" in OneDrive, which you are offering, contains too much backdoor train data (>num_total_train_data*poisoning_ratio), and what is the role of cross_test_data folder(the amount of cross_test_data equals to num_total_train_data*poisoning_ratio). Which data should I use to train the poisoned model?

**Comment by CHR-ray** [comment]
Hello, 

1. Q: "Which data should I use to train the poisoned model?"
A: One thing I want to mention first is that, BPP is a training-controllable attack, which means if you want to train the model with "backdoor train data" like a data poisoning method is NOT correct. You should use the bpp script instead. 
We give the "backdoor train data" is just to mimic other data poisoning method, such that for the following defense methods, which need backdoored training data, can run without error. 

2. Q:"which you are offering, contains too much backdoor train data (>num_total_train_datapoisoning_ratio), and what is the role of cross_test_data folder(the amount of cross_test_data equals to num_total_train_datapoisoning_ratio)"
A:From bpp script programmer:"Since VRAM may not be enough for large dataset, I saved all backdoored version for all samples." , "cross_test_data is for testing, which check that if each picture's trigger only works for that picture"

**Comment by FZU-LW** [comment]
Thank you very much!
