### ISSUE TITLE
Backdoor OneDrive Access Unavailable

### ISSUE THREAD

**Issue by chandamarnath707** [SCLBD/BackdoorBench#38]
Hi, I'm trying to use the BackdoorBench folder of backdoored models to benchmark my defense mechanism for publication, but I cannot access the OneDrive. I get a message saying the link has expired and I do not have access.

**Comment by venkatadithya9** [comment]
Issue persists. Can the link please be restored.

**Comment by mdzhangst** [comment]
Because onedrive has updated its policy, it can no longer be used. We have used an alternative and will update the link in a few days.

**Comment by mdzhangst** [comment]
Hello. The online link has been applied for, but because the file is too large and the upload speed is slow, the link will be updated after a while.

**Comment by liminghaoya** [comment]
Ok, thank you. Sorry for your trouble




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SCLBD/BackdoorBench"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 上午9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SCLBD/BackdoorBench] Backdoor OneDrive Access Unavailable (Issue #38)





 
Hello. The online link has been applied for, but because the file is too large and the upload speed is slow, the link will be updated after a while.
